In [ ]:
import numpy as np

# 1. Create arrays
arr1 = np.arange(0, 21)  # 1D array from 0 to 20
arr2 = np.random.randint(10, 100, size=(4, 5))  # 2D array 4x5 random ints 10–99
identity_matrix = np.eye(3)  # 3x3 identity matrix

print("1D Array:\n", arr1)
print("\n2D Array (4x5):\n", arr2)
print("\nIdentity Matrix (3x3):\n", identity_matrix)

# 2. Mean, median, std of 2D array
print("\nMean of 2D array:", np.mean(arr2))
print("Median of 2D array:", np.median(arr2))
print("Standard Deviation of 2D array:", np.std(arr2))

# 3. Slice operations
print("\nSecond row:", arr2[1])
print("Third column:", arr2[:, 2])

# 4. Element-wise multiplication
arr3 = np.random.randint(1, 10, size=(4, 5))
print("\nAnother 4x5 Array:\n", arr3)
print("\nElement-wise Multiplication:\n", arr2 * arr3)



1D Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

2D Array (4x5):
 [[86 93 15 75 34]
 [57 30 86 93 83]
 [43 36 50 88 85]
 [90 71 70 55 24]]

Identity Matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Mean of 2D array: 63.2
Median of 2D array: 70.5
Standard Deviation of 2D array: 25.005199459312458

Second row: [57 30 86 93 83]
Third column: [15 86 50 70]

Another 4x5 Array:
 [[2 7 8 3 9]
 [9 7 5 9 1]
 [2 5 7 8 2]
 [1 8 9 9 1]]

Element-wise Multiplication:
 [[172 651 120 225 306]
 [513 210 430 837  83]
 [ 86 180 350 704 170]
 [ 90 568 630 495  24]]


In [2]:
 #Broadcasting and Reshaping

# 1. Create 1D array and reshape
import numpy as np

arr = np.arange(1, 17)  # 1D array from 1 to 16
matrix = arr.reshape(4, 4)
print("Original 4x4 Matrix:\n", matrix)

# 2. Add [1,2,3,4] to each row (broadcasting)
add_arr = np.array([1, 2, 3, 4])
result = matrix + add_arr
print("\nAfter Broadcasting Addition:\n", result)

# 3. Flatten back to 1D
flattened = result.flatten()
print("\nFlattened 1D Array:\n", flattened)


Original 4x4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

After Broadcasting Addition:
 [[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]
 [14 16 18 20]]

Flattened 1D Array:
 [ 2  4  6  8  6  8 10 12 10 12 14 16 14 16 18 20]
